# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    groups:
      patches-and-minors:
        update-types:
          - 'patch'
          - 'minor'

      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'

      jest:
        patterns:
          - 'jest'
          - '@jest/*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      actions:
        update-types:
          - 'patch'
          - 'minor'
          - 'major'
