version: 2
jobs:
  build:
    docker:
      # https://circleci.com/developer/images/image/cimg/node
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout:
          method: blobless

      - run:
          name: Install pnpm package manager
          command: sudo npm install -g pnpm@11
      - run:
          name: Install Dependencies
          command: pnpm install
      - run: pnpm test
