version: 2
jobs:
  build:
    docker:
      # https://circleci.com/developer/images/image/cimg/node
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
